export const initialArticles = [
    {id: 111, title: 'Puss in Boots: The Last Wish', overview: 'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.'},
    {id: 222, title: 'Avatar: The Way of Water', overview: 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.'},
    {id: 333, title: 'Dog Gone', overview: 'When his beloved dog goes missing, a young man embarks on an incredible search with his parents to find him and give him life-saving medication.'},
    {id: 444, title: 'The Menu', overview: 'A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.'},
	{id: 555, title: 'M3GAN', overview: 'A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll\'s programming works too well, she becomes overprotective of her new friend with terrifying results.'},
{id: 666, title: 'The Pale Blue Eye', overview: 'West Point, New York, 1830. When a cadet at the burgeoning military academy is found hanged with his heart cut out, the top brass summons former New York City constable Augustus Landor to investigate. While attempting to solve this grisly mystery, the reluctant detective engages the help of one of the cadets: a strange but brilliant young fellow by the name of Edgar Allan Poe'},
{id: 777, title: 'The Old Way', overview: 'An old gunslinger and his daughter must face the consequences of his past, when the son of a man he murdered years ago arrives to take his revenge.'},
{id: 888, title: 'Devotion', overview: 'The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy\'s most celebrated wingmen.'},
  ]